version: "4.15.0"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-as
    restart: always
    volumes:
      - ./eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      se4as-network:
        ipv4_address: 173.30.0.100
    ports:
      - "1883:1883"
      - "9001:9001"



  simulator1:
    container_name: simulator1
    build:
      context: ./simulator1/
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mosquitto
    networks:
      se4as-network:
        ipv4_address: 173.30.0.101
        
  simulatorwth:
    container_name: simulatorwth
    build:
      context: ./simulatorwth/
      dockerfile: ./Dockerfile

    restart: always
    depends_on:
      - mosquitto
    networks:
      se4as-network:
        ipv4_address: 173.30.0.102

  #MAPE-K
  monitor:
    container_name: monitor-as
    build:
      context: ./monitor/
      dockerfile: ./Dockerfile
    volumes:
      - ./monitor/:/usr/src/app/
    restart: always
    networks:
      se4as-network:
        ipv4_address: 173.30.0.103
    depends_on:
      - mosquitto
      - simulator1
      
 
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"        
    restart: always
    volumes:
      - "influxdb-data:/var/lib/influxdb"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=greenhouse
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=b320d3x72fwC6N-E07xD-pa1_B9jm6Wi2cNLH1ZPDqe2qkA3e_VbQNGrHwTfrPnHlUFmuea7PqCSQXFAmxJDPQ==
    networks:
      se4as-network:
        ipv4_address: 173.30.0.104
    depends_on:
      - mosquitto
      - monitor
      - simulator1
      - simulatorwth

  
  analyzer:
    container_name: analyzer-as
    build:
      context: ./analyzer/
      dockerfile: ./Dockerfile
    volumes:
      - ./analyzer/:/usr/src/app/
    restart: always
    networks:
      se4as-network:
        ipv4_address: 173.30.0.105
    depends_on:
      - mosquitto
      - influxdb
      - monitor 
      - simulator1
      - simulatorwth

  
  planner:
    container_name: planner-as
    build:
      context: ./planner/
      dockerfile: ./Dockerfile
    volumes:
      - ./planner/:/usr/src/app/
    restart: always
    networks:
      se4as-network:
        ipv4_address: 173.30.0.106
    depends_on:
      - mosquitto
      - simulatorwth    
      - analyzer
      


  executor:
    container_name: executor-as
    build:
      context: ./executor/
      dockerfile: ./Dockerfile
    volumes:
      - ./executor/:/usr/src/app/
    restart: always 

    networks:
      se4as-network:
        ipv4_address: 173.30.0.106
    depends_on:
      - mosquitto
      - planner
      - analyzer
      - influxdb
      - monitor 
      - simulator1
      - simulatorwth




networks:
  se4as-network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.30.0.0/16

volumes:
  influxdb-data: {}
